[package]
name = "msign"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
ed25519-dalek = { version = "2", features = ["rand_core"] }
rand_core = { version = "0.6", features = ["getrandom"] }
sha2 = "0.10"
base64 = "0.22"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
tar = "0.4"
flate2 = "1"
tempfile = "3"