use std::{
    fs::{self, File},
    io::Write,
    path::Path,
};

use anyhow::{Context, Result};
use flate2::{write::GzEncoder, Compression};
use tar::Builder;
use tempfile::tempdir;

use crate::{cli::MockPkgArgs, fs as xfs};

pub fn run(args: MockPkgArgs) -> Result<()> {
    xfs::ensure_parent(&args.output)?;

    let temp = tempdir().context("failed to create temporary directory")?;
    let app_dir = temp.path().join(format!("{}.app", args.name));

    create_mock_app(&app_dir, &args)?;

    create_pkg_from_dir(&app_dir, &args.output)?;

    println!("created mock pkg: {}", args.output.display());

    Ok(())
}

fn create_mock_app(app_dir: &Path, args: &MockPkgArgs) -> Result<()> {
    xfs::recreate_dir(app_dir)?;

    fs::create_dir_all(app_dir.join("assets"))
        .with_context(|| format!("failed to create assets dir: {}", app_dir.display()))?;

    write_about_toml(app_dir, args)?;
    write_entry_elf_mock(app_dir)?;
    write_icon_mock(app_dir)?;
    write_readme(app_dir)?;

    Ok(())
}

fn write_about_toml(app_dir: &Path, args: &MockPkgArgs) -> Result<()> {
    let about = format!(
        r#"name = "{}"
bundle_id = "{}"
version = "{}"
developer = "{}"
entry = "entry.elf"
description = "Mock package for mochiOS devkit tests"
icon = "assets/icon.png"
"#,
        args.name, args.bundle_id, args.version, args.developer
    );

    fs::write(app_dir.join("about.toml"), about).context("failed to write about.toml")
}

fn write_entry_elf_mock(app_dir: &Path) -> Result<()> {
    let mut file = File::create(app_dir.join("entry.elf")).context("failed to create entry.elf")?;

    file.write_all(b"\x7fELF")
        .context("failed to write ELF magic")?;

    file.write_all(b"\nmock mochiOS executable\n")
        .context("failed to write mock executable")?;

    Ok(())
}

fn write_icon_mock(app_dir: &Path) -> Result<()> {
    fs::write(app_dir.join("assets/icon.png"), "mock icon\n").context("failed to write mock icon")
}

fn write_readme(app_dir: &Path) -> Result<()> {
    fs::write(
        app_dir.join("README.txt"),
        "This is a mock mochiOS package generated by xtask.\n",
    )
    .context("failed to write README.txt")
}

fn create_pkg_from_dir(app_dir: &Path, output: &Path) -> Result<()> {
    let file =
        File::create(output).with_context(|| format!("failed to create {}", output.display()))?;

    let encoder = GzEncoder::new(file, Compression::default());
    let mut tar = Builder::new(encoder);

    append_dir_contents(&mut tar, app_dir, app_dir)?;

    tar.finish().context("failed to finish tar archive")?;

    Ok(())
}

fn append_dir_contents<W: Write>(tar: &mut Builder<W>, root: &Path, dir: &Path) -> Result<()> {
    let mut entries = fs::read_dir(dir)
        .with_context(|| format!("failed to read dir {}", dir.display()))?
        .collect::<Result<Vec<_>, _>>()
        .with_context(|| format!("failed to collect dir entries {}", dir.display()))?;

    entries.sort_by_key(|entry| entry.path());

    for entry in entries {
        let path = entry.path();
        let relative = path
            .strip_prefix(root)
            .context("failed to create relative path")?;

        if path.is_dir() {
            append_dir_contents(tar, root, &path)?;
        } else if path.is_file() {
            tar.append_path_with_name(&path, relative)
                .with_context(|| {
                    format!(
                        "failed to append {} as {}",
                        path.display(),
                        relative.display()
                    )
                })?;
        }
    }

    Ok(())
}
